on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch: {}

name: Update readme
jobs:
  update_readme:
    name: Update readme
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - name: Python Poetry Action
        uses: abatilo/actions-poetry@v2.1.4
      - run: poetry install
      - name: Update readme
        uses: technote-space/create-pr-action@v2
        with:
          EXECUTE_COMMANDS: |
            poetry run python ./.github/workflows/scripts/generate-docs.py
            npx prettier . --write
          COMMIT_MESSAGE: "chore: update ${{ matrix.name }} readme"
          COMMIT_NAME: "GitHub Actions"
          COMMIT_EMAIL: "example@example.com"
          PR_BRANCH_NAME: "chore-${{ matrix.name }}-update-readme-${PR_ID}"
          PR_TITLE: "chore: update ${{ matrix.name }} readme"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
